name: test-workflow

on:
  workflow_dispatch:


jobs:
  Execute:
        name: Use custom action
        runs-on: ubuntu-latest
        with:
          name: transferfile
          source: ./transferfile.txt
          destination: /
        steps:
      - uses: actions/checkout@v3
      - uses: ./
