name: test-workflow

on:
  workflow_dispatch:


jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

  Execute:
      - name: Use custom action
        runs-on: ubuntu-latest
        uses: ./
        with:
          name: transferfile
          source: ./transferfile.txt
          destination: /
       