name: test-workflow

on:
  workflow_dispatch:


jobs:
  Execute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use custom action
        uses: ./.github/actions/action.yml
        with:
          name: transferfile
          source: ./transferfile.txt
          destination: /
       