name: test-workflow

on:
  workflow_dispatch:

jobs:
  Execute:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  

      - name: Use custom action
        uses: /
        with:
          name: transferfile
          source: ./transferfile.txt  
          destination: /  
          ssh_key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}  
          instance_ip: ${{ secrets.EC2_HOST }}  